#!/usr/bin/env python3
"""bin2h.py <binary_file> <variable_name>
Generates a C header with the binary content as a static byte array.
Usage: python bin2h.py file.dll my_dll > include/my_dll_blob.h
"""
import sys

def main():
    if len(sys.argv) != 3:
        print(f"Usage: {sys.argv[0]} <file> <varname>", file=sys.stderr)
        sys.exit(1)

    path = sys.argv[1]
    name = sys.argv[2]

    with open(path, "rb") as f:
        data = f.read()

    print(f"/* auto-generated by bin2h.py — do not edit */")
    print(f"static const unsigned char {name}[] = {{")
    for i, b in enumerate(data):
        if i % 16 == 0:
            print("  ", end="")
        print(f"0x{b:02x},", end="")
        if i % 16 == 15:
            print()
        else:
            print(" ", end="")
    if len(data) % 16 != 0:
        print()
    print("};")
    print(f"static const unsigned int {name}_len = {len(data)};")

if __name__ == "__main__":
    main()
