#!/usr/bin/env python3
"""bin2h.py [--xor HEXKEY] [--nibble] <binary_file> <variable_name>
Generates a C header with the binary content as a static byte array.
  --xor HEXKEY  rotating XOR key (hex, e.g. 3BA7C15E). Adds _xor_key array.
  --nibble      nibble-split after XOR: each byte -> two nibbles (0-15).
                Halves per-byte entropy (max 0.5 normalized). Adds _enc_len.
Usage: python bin2h.py file.dll my_dll > include/my_dll_blob.h
       python bin2h.py --xor 3BA7C15E --nibble file.dll my_dll > out.h
"""
import sys

def main():
    args = sys.argv[1:]
    xor_key = None
    nibble = False

    while args and args[0].startswith("--"):
        if args[0] == "--xor" and len(args) >= 2:
            raw = args[1]
            if len(raw) % 2 != 0 or not all(c in "0123456789abcdefABCDEF" for c in raw):
                print("--xor key must be even-length hex string", file=sys.stderr)
                sys.exit(1)
            xor_key = bytes.fromhex(raw)
            args = args[2:]
        elif args[0] == "--nibble":
            nibble = True
            args = args[1:]
        else:
            break

    if len(args) != 2:
        print(f"Usage: {sys.argv[0]} [--xor HEXKEY] [--nibble] <file> <varname>",
              file=sys.stderr)
        sys.exit(1)

    path, name = args

    with open(path, "rb") as f:
        data = f.read()

    decoded_len = len(data)

    if xor_key:
        data = bytes(b ^ xor_key[i % len(xor_key)] for i, b in enumerate(data))

    if nibble:
        encoded = bytearray()
        for b in data:
            encoded.append(b >> 4)
            encoded.append(b & 0x0F)
        data = bytes(encoded)

    print(f"/* auto-generated by bin2h.py — do not edit */")
    print(f"static const unsigned char {name}[] = {{")
    for i, b in enumerate(data):
        if i % 16 == 0:
            print("  ", end="")
        print(f"0x{b:02x},", end="")
        if i % 16 == 15:
            print()
        else:
            print(" ", end="")
    if len(data) % 16 != 0:
        print()
    print("};")

    if nibble:
        # _len = decoded (actual PE size used by injection code)
        # _enc_len = encoded (nibble array size, 2x)
        print(f"static const unsigned int {name}_len = {decoded_len};")
        print(f"static const unsigned int {name}_enc_len = {len(data)};")
    else:
        print(f"static const unsigned int {name}_len = {len(data)};")

    if xor_key:
        key_bytes = ", ".join(f"0x{b:02x}" for b in xor_key)
        print(f"static const unsigned char {name}_xor_key[] = {{{key_bytes}}};")
        print(f"static const unsigned int {name}_xor_key_len = {len(xor_key)};")

if __name__ == "__main__":
    main()
